### ISSUE TITLE
Annotate persistent volume claim to influence bucket name

### ISSUE THREAD

**Issue by sjaek** [ctrox/csi-s3#14]
First of all great work on this CSI plugin. 

I tested it in managed kubernetes cluster at digital ocean and it works pretty well. **However I would like to influence how the buckets are named, now it gives me buckets called pvc- followed by some UUID.** Having some control over the bucket naming would make it more clear what bucket is used for what. 

I tried to make a persistent volume and claim manually by referencing a volumeHandle (and created the bucket beforehand) and volumeName on the claim. Unfortunately this prevented the container from starting, it keeps waiting in the ContainerCreating status indefinitely. The same configuration with only a persistent volume claim (without the volumehandle) works fine, it will create it's own PersistentVolume and mounts it in the container, and the container starts correctly. 

It doesn't seem seem to work for me to make my own PV and use it with the driver, or I'm doing something wrong. **But even more convenient would be if I could place an annotation on the PVC that gives a hint to the provisioner as to which bucketname to create/use.**

E.g.:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  annotations:
    ch.ctrox.csi.s3-driver/bucketname: "mybucket"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-s3
```

The PV/PVC config I tried but didn't get to work looked like this:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  storageClassName: csi-s3
  accessModes:
  - ReadWriteMany
  capacity: 
    storage: 1Gi
  csi:
    driver: ch.ctrox.csi.s3-driver
    volumeHandle: mybucketname
    # I added this (volumeAttributes.mounter: s3fs) because I saw this in the generated PV
    volumeAttributes:
      mounter: s3fs
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-s3
  volumeName: my-pv
```
When I don't create the PV and removing the volumeName from the PVC it works fine, but then the bucketname is pvc-[uuid]. 

Maybe I'm missing something, or lack some configuration on the PV, but just having an annotation on the PVC would be even more convenient.
