### ISSUE TITLE
No matches for kind "StatefulSet" in version "apps/v1beta1"

### ISSUE THREAD

**Issue by hetii** [ctrox/csi-s3#35]
Hi, I try to test this project but get following error:

	kubectl apply -f https://raw.githubusercontent.com/ctrox/csi-s3/master/deploy/kubernetes/attacher.yaml
	serviceaccount/csi-attacher-sa unchanged
	clusterrole.rbac.authorization.k8s.io/external-attacher-runner unchanged
	clusterrolebinding.rbac.authorization.k8s.io/csi-attacher-role unchanged
	service/csi-attacher-s3 unchanged
	error: unable to recognize "https://raw.githubusercontent.com/ctrox/csi-s3/master/deploy/kubernetes/attacher.yaml": no matches for kind "StatefulSet" in version "apps/v1beta1"

Kubernets version:

	Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-07T14:04:52Z", GoVersion:"go1.13.12", Compiler:"gc", Platform:"linux/amd64"}
	Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bytecarver** [comment]
This workaround helps:

```yaml
kind: StatefulSet
apiVersion: apps/v1
```

and in Kubernetes 1.20 selector must be specified for StatefulSet:
```yaml
metadata:
   name: csi-provisioner-s3
   namespace: csi-s3
spec:
  selector:
    matchLabels:
      app: "csi-provisioner-s3"
  serviceName: "csi-provisioner-s3"

```
