### ISSUE TITLE
Unable to Mount volume at Pod

### ISSUE THREAD

**Issue by leyi-bc** [ctrox/csi-s3#77]
hi,can you help me solve this problem?
Unable to attach or mount volumes: unmounted volumes=[webroot], unattached volumes=[istio-token istio-podinfo kube-api-access-g9wh7 webroot istiod-ca-cert istio-data istio-envoy]: timed out waiting for the condition

I think there is no problem with my PVC

Name:          csi-s3-existing-bucket
Namespace:     default
StorageClass:  csi-s3-existing-bucket
Status:        Bound
Volume:        pvc-68bdbede-e355-48ce-9ce7-7d47a9219da8
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: ch.ctrox.csi.s3-driver
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       csi-s3-test-nginx
Events:        <none>

`apiVersion: v1
kind: Pod
metadata:
  name: csi-s3-test-nginx
  namespace: default
spec:
  containers:
   - name: csi-s3-test-nginx
     image: nginx
     volumeMounts:
       - mountPath: /var/lib/www/html
         name: webroot
  volumes:
   - name: webroot
     persistentVolumeClaim:
       claimName: csi-s3-existing-bucket
       readOnly: false
  `

**Comment by leyi-bc** [comment]
![image](https://user-images.githubusercontent.com/82554168/179176966-ef08a97e-cbd1-4a11-a411-18bdbe145f15.png)
![image](https://user-images.githubusercontent.com/82554168/179177034-dff67f5e-9665-4016-81dc-37d565e77409.png)

**Comment by fallmo** [comment]
I had the same problem, I looked at the logs of the `csi-attacher-s3` pod, first i saw `Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource`. I figured it was a k8s version issue, so I updated the container image of the csi-attacher stateful set, from v2.2.1 to canary (the latest). 

```bash
kubectl -n kube-system set image statefulset/csi-attacher-s3 csi-attacher=quay.io/k8scsi/csi-attacher:canary
```

Next I got a permission error: `v1.VolumeAttachment: failed to list *v1.VolumeAttachment: volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:csi-attacher-sa" cannot list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope. 

I tried to modify the role bindings but I couldn't find the right combinations so I ended up giving the csi-attacher-sa service account cluster-admin privileges as shown below:
```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-all
subjects:
  - kind: ServiceAccount
    name: csi-attacher-sa
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```
