### ISSUE TITLE
FEAT/BUG: Mount statically created PersistentVolume

### ISSUE THREAD

**Issue by lgiedrius** [ctrox/csi-s3#87]
Adding pre-setup PersistentVolume BIND's successfully, but fails to mount:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  name: s3-pv-test
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: s3-pv-test
    namespace: s3-test
  csi:
    controllerExpandSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
    controllerPublishSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
    driver: ch.ctrox.csi.s3-driver
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
    volumeAttributes:
      bucket: existing-bucket-name
      mounter: rclone
    volumeHandle: existing-bucket-name
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
  name: s3-pv-test
  namespace: s3-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: s3-pv-test
```
Adding such PVC to POD fails to create container. Errors are visible in the CSI NODE POD: 
```
I0809 09:45:02.363760       1 utils.go:97] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0809 09:45:03.361599       1 utils.go:97] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0809 09:45:03.362544       1 utils.go:97] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0809 09:45:03.363497       1 utils.go:97] GRPC call: /csi.v1.Node/NodeStageVolume
E0809 09:45:03.377320       1 utils.go:101] GRPC error: The specified key does not exist.
```
